#!/usr/bin/python

from optparse import OptionParser, Option
import os
import sys

def main():
    def info(line):
        if options.verbose:
            sys.stderr.write(line)
            sys.stderr.write('\n')
    
    def error(line):
        sys.stderr.write(line)
        sys.stderr.write('\n')
        exit(1)
    
    parser = OptionParser(option_list=(
        Option('-v', '--verbose', action='store_true', default=False),
    ))
    options, args = parser.parse_args()
    
    for path in args:
        try:
            os.makedirs(path)
        except (OSError, IOError), exc:
            if os.path.isdir(path):
                info('Path already exists: %s' % path)
            else:
                error('%s: %s' % (exc.strerror, path))
        else:
            info('Created directory %s' % path)
        
        fragments = path.split(os.path.sep)
        for i in xrange(len(fragments)):
            filename = os.path.sep.join(fragments[:i+1] + ['__init__.py'])
            if not os.path.isfile(filename):
                try:
                    open(filename, 'w').close()
                except (OSError, IOError), exc:
                    if os.path.isfile(path):
                        info('File already exists: %s' % filename)
                    else:
                        error('%s: %s' % (exc.strerror, filename))
                else:
                    info('Created file %s' % filename)
            else:
                info('File already exists: %s' % filename)

if __name__ == '__main__':
    main()

